version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::711232731442:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-146RBAX8V4BJG"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::711232731442:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-E0OZVZWW8CDV"
cloudformation_execution_role = "arn:aws:iam::711232731442:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-160DD90PBH0IM"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1840so4m62j0l"
image_repository = ""
region = "eu-central-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::711232731442:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-95DQYL17PI6G"
cloudformation_execution_role = "arn:aws:iam::711232731442:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1IPHBBNDOBD2W"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-13222md8s5u2p"
image_repository = ""
region = "eu-central-1"
